openapi: 3.0.0
info:
  title: Application API
  description: This is a advanced node js repos' servers api
  version: 0.1.9

servers:
  - url: http://localhost:3000/
    description: Local server
  - url: http://production.com/
    description: production server of application

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Arthur Dent
      # Both properties are required
      required:
        - id
        - name

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Gives the list of all the available users
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/User'

  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: Information of user with specific id.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: OK
          content: 
            application/json: 
              schema: 
                $ref: '#components/schemas/User'

  /user:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/User'
      responses:
        "201":
          description: Created
